/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#3e4949',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'tertiary': '#8f4c00',
        'on-secondary-fixed': '#011d35',
        'surface-container-highest': '#dae2fd',
        'background': '#faf8ff',
        'surface-container-high': '#e2e7ff',
        'inverse-on-surface': '#eef0ff',
        'on-primary-fixed': '#002021',
        'on-background': '#131b2e',
        'on-tertiary-container': '#ffffff',
        'on-primary-fixed-variant': '#004f52',
        'primary': '#00686c',
        'tertiary-fixed': '#ffdcc3',
        'secondary-fixed': '#d1e4ff',
        'primary-container': '#0e8388',
        'surface-tint': '#00696d',
        'surface-container': '#eaedff',
        'on-secondary-container': '#4b637e',
        'outline-variant': '#bdc9c9',
        'on-primary-container': '#ffffff',
        'on-error-container': '#93000a',
        'error': '#ba1a1a',
        'primary-fixed-dim': '#77d5da',
        'surface': '#faf8ff',
        'surface-bright': '#faf8ff',
        'secondary-fixed-dim': '#b0c9e8',
        'tertiary-container': '#b36100',
        'on-tertiary-fixed-variant': '#6e3900',
        'inverse-primary': '#77d5da',
        'tertiary-fixed-dim': '#ffb77d',
        'error-container': '#ffdad6',
        'primary-fixed': '#94f2f7',
        'inverse-surface': '#283044',
        'surface-dim': '#d2d9f4',
        'on-tertiary-fixed': '#2f1500',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#314863',
        'on-surface': '#131b2e',
        'on-error': '#ffffff',
        'secondary': '#49607c',
        'secondary-container': '#c7dfff',
        'surface-variant': '#dae2fd',
        'outline': '#6e797a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'gutter-mobile': '1rem',
        'margin-desktop': '3rem',
        'margin-tablet': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'space-sm': '0.5rem',
        'space-lg': '1.5rem',
        'gutter-tablet': '1.5rem',
        'space-2xs': '0.125rem',
        'gutter-desktop': '1.5rem',
        'space-xl': '2rem',
        'space-xs': '0.25rem',
        'space-md': '0.75rem',
        'max-width': '80rem',
        'margin-mobile': '1rem',
        'space-base': '1rem',
      },
      fontFamily: {
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-sm': ['Manrope', 'sans-serif'],
        'body-lg': ['Source Sans 3', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'label-caps': ['Manrope', 'sans-serif'],
        'code': ['monospace'],
        'body-md': ['Source Sans 3', 'sans-serif'],
        'headline-xl': ['Manrope', 'sans-serif'],
        'label-md': ['Manrope', 'sans-serif'],
        'label-lg': ['Manrope', 'sans-serif'],
        'headline-xl-mobile': ['Manrope', 'sans-serif'],
        'display-lg-mobile': ['Manrope', 'sans-serif'],
        'display-lg': ['Manrope', 'sans-serif'],
        'body-sm': ['Source Sans 3', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['1.375rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['1.125rem', { lineHeight: '1.5rem', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75rem', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.015em', fontWeight: '600' }],
        'label-caps': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.06em', fontWeight: '700' }],
        'code': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0em', fontWeight: '500' }],
        'body-md': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0em', fontWeight: '400' }],
        'headline-xl': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-lg': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-xl-mobile': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.015em', fontWeight: '700' }],
        'display-lg-mobile': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['3.5rem', { lineHeight: '4rem', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-sm': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.005em', fontWeight: '400' }],
      },
      maxWidth: {
        'max-width': '80rem',
      },
    },
  },
  plugins: [],
};
